### ISSUE TITLE
有一个不明白的问题？

### ISSUE THREAD

**Issue by changgongcheng** [Thomas-wyh/Ada-NETS#6]
作者，您好，关于struct space，如果struct_space能改变特征集的整体结构，那就可以直接很好的聚类或者识别了，所以不太明白后续的自适应的意义有多大？

**Comment by Thomas-wyh** [comment]
Please be patient and read the Experiments section in the paper first.
The Table3 and the 1st paragraph in Section4.3 will answer your question.
